dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - docker

env:
  global:
    - LUAROCKS=2.4.2
    - OPENSSL=1.0.2l
    - CASSANDRA=2.2.8
    - OPENRESTY_BASE=1.11.2.4
    - OPENRESTY_LATEST=1.11.2.4
    - OPENRESTY=$OPENRESTY_BASE
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit

before_install:
  - source .ci/setup_env.sh

install:
  - make dev

script:
  - .ci/run_tests.sh

deploy:
  if: tag =~ 0.
  script: .ci/trigger-travis.sh $TRAVIS_ACCESS_TOKEN
  env:
    - TEST_SUITE=none

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
